---
title: "Project 1: Don’t read a lot of books…with Voyant!"
date: "19/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Collaborators: Vir Singh, Krisha Vaishnav, Paritosh Panda

**Leader**: Vir Singh

**Research Hypothesis**: The social upheavals due to the Revolutions of 1848 in Europe affect Charles Dickens’ writing in terms of frequency, vocabulary, and geographical coverage. 

**Corpus Description**
*Corpus 1* covers six books written by Dickens before 1848
*Corpus 2* covers thirteen books written by Dickens since 1848

**Summary Paragraph**
*Longest*: Dombey and Sons (1848)
*Shortest*: A Message From The Sea (1860)
*Total*: 19 books, almost 4 million total words and 41,724 unique word forms.
Most frequent words in the corpus: Mr (28,535); said (27,173); little (10,197); Mrs (8,390); sir (8,230)

<iframe style='width: 717px; height: 221px;' src='https://voyant-tools.org/tool/Summary/?corpus=affb58168dd59d2a279b36e264b6829c'data-external = '1'></iframe>

**Tool 1: Frequency Comparison**
  The advent of the industrial revolution brought about major changes in the economic and social spheres of everyday life. More specifically, after the liberation movements in 1848, we expected Dickens’ writing to reflect the current situation through more mentions about the repercussions of the industrial revolution in daily life. For example, a greater divide between the classes and thus increased mentions in his books published 1848 onwards. To check for this, we piped together different search terms that encapsulate the upper and lower classes:

madam|master*|mistress*|lady|lord*|vicar|begging|poor|peasant*|orphan*|servant*|charity|workhouse*|union*|poverty

<iframe style='width: 509px; height: 381px;' src='https://voyant-tools.org/tool/Trends/?query=madam%7Cmaster*%7Cmistress*%7Clady%7Clord*%7Cvicar%7Cbegging%7Cpoor%7Cpeasant*%7Corphan*%7Cservant*%7Ccharity%7Cworkhouse*%7Cunion*%7Cpoverty&corpus=e1ff4a9aaff9690c55ac866c468bdc86' data-external='1'></iframe>

  The graph sees its peak in the 1851 book, A Child’s History of England. The book is a commentary about the past English monarchs, the popish clergy, and the violence that took place in the past. The book is about the different societal classes and thus will have a higher mention of words pertaining to class (Jann 199). Additionally, Oliver Twist has the second highest frequency of these terms, as it is a socially accurate portrayal of the social classes in Victorian society. This, too, corresponds with the Poor Law that was ratified in 1834 (Dickens: Law and Politics), that set up workhouses, in which lower class individuals were made to work and live in deplorable conditions. The effects of this law were seen in the few years after its implementation, following which Oliver Twist was published, in 1838. The concept of workhouses and devastating poverty were central to the novel. Consequently, one can conclude that this functions as an allegorical response to the political and social realities of Britain in the 1830s and 40s.

  Interestingly, Great Expectations (1961) had the second lowest frequency of these terms. A haunting and desolate portrayal of Victorian class mobility, this novel based on Dickens’ own childhood experiences is primarily focused on the psychological growth and development that comes from rapid class mobility (Bowen). A very sparsely event-based novel, the extensive examination of psychology and thought patterns reflected the low frequency of terms that was observed, despite the thematic elements of the book representing the class structure of Victorian society.

  Industrialisation also brought with it a change in the mindset of people, of how they perceive money and their feelings towards it. To measure this we searched:

pride*|greed*|passion*|envy*|desire*|wealth*

<iframe style='width: 509px; height: 381px;' src='https://voyant-tools.org/tool/Trends/?query=pride*%7Cgreed*%7Cpassion*%7Cenvy*%7Cdesire*%7Cwealth*&corpus=e1ff4a9aaff9690c55ac866c468bdc86' data-external='1'></iframe>

  This graph also shows no significant pattern, with its highest point in A Christmas Carol, a book about human goodness and benevolence. The book talks about the virtues of kindness and compassion, and thus also mentioned the opposite end of the spectrum (pride and greed).

  The industrial revolution resulted in the exploitation of the lower class (). Children were forced to work in factories and workhouses from a very young age, not even receiving their entire education. A situation Dickens himself personally experienced. We created a cluster of words that assess this situation:
  
hungry|tired|starving|homeless|death|orphanage|workhouse|labour||squalor|polish*|wage*|meagre|misery

<iframe style='width: 509px; height: 381px;' src='https://voyant-tools.org/tool/Trends/?query=hungry%7Ctired%7Cstarving%7Chomeless%7Cdeath%7Corphanage%7Cworkhouse%7Clabour%7C%7Csqualor%7Cpolish*%7Cwage*%7Cmeagre%7Cmisery&corpus=e1ff4a9aaff9690c55ac866c468bdc86' data-external='1'></iframe>

We also searched for words closely related with the processes of industrialisation to see how their usage had changed:

factory|work*|wealth*|industry|production|machine*

<iframe style='width: 509px; height: 381px;' src='https://voyant-tools.org/tool/Trends/?query=factory%7Cwork*%7Cwealth*%7Cindustry%7Cproduction%7Cmachine*&corpus=e1ff4a9aaff9690c55ac866c468bdc86' data-external='1'></iframe>

  All clusters present a random trend from which no meaningful conclusion can be drawn about how Dickens’ writing style changed after the revolution hit its peak in 1848, the liberation movement. The top most frequent words, “mr”, “said”, “little” etc., also do not tell us anything about how industrialisation might have affected his writing, if at all.

<iframe style='width: 509px; height: 381px;' src='https://voyant-tools.org/tool/CorpusTerms/?corpus=e1ff4a9aaff9690c55ac866c468bdc86' data-external='1'></iframe>

  In the examination and presentation of the statistical trends that emerge when the literature of Charles Dickens is analysed, the advent of industrialization, and the liberation movement across Europe, saw a change in the thematic elements that came to define his books. There is a lack of congruence in the results when word frequency of relevant, thematic words is analysed. This implies that the allegorical manner of writing does not capture the increasing thematic focus on the horrors of industrialization, child labour, and the growing class divide.
  
**Tool 2: Collocation and Correlation**
	
	Our results from the frequency comparison lay in the realm of political social context, rather than the establishment of an overarching, chronological trend. For this reason, in the collocation and correlation comparison, the context in which these words are used was analysed, in the absence of any discernible trends in the frequency comparison. It is highly possible that the context in which these words are used will change before and after the groundbreaking social and political effects of the industrial revolution were reflected in society. 
	
  Initially this analysis was not leading to much. We tried looking at similar word clusters as we did for our frequency study. While trying to look up class distinctions we used the words “poor” and “servant” to check what kinds of sentiments Dickens was feeling towards class at the time.

  For the word “poor” a gendered distinction was observed, between the two time periods. For the initial corpus, i.e. pre 1848, we found that poor was associated with “fellow”, whereas for the post 1848 corpus, “poor” was associated with “girl”. We could conclude from this that Dickens had begun to associate femininity with poverty. It is possible that with the advent of the industrial revolution the earning capacity of men had increased while women would continue to stay at home not earning any money. This association seemed farfetched to us, however. It did not seem to make any sense that the industrial revolution would change someone’s perception of the earning power of women , especially for the worse. Moreover, it seemed more likely that in both cases the word poor is not referring to a financial situation but rather poor is being used to showcase a feeling of pity, i.e., “oh no, that poor girl” or “the poor fellow drowned in the lake”.

  The word "hunger" showed some interesting results. While for corpus 1, the word had no collocate of any interest, for corpus 2 the word greedy popped up as a collocate. This is an interesting sphere of examination, as greed is a common theme associated with the rising capitalistic sentiment brought about by burgeoning industrialisation. It is possible that the popular sentiment at the time was that the masses were being forced to go hungry as a result of the greed of the few. It is also likely that greed is not being used in reference to food but rather is reference to power and wealth. Perhaps the great industrialists of the past were hungry and greedy for money and this is the sentiment that is being brought out by Dickens (Shihada 42).
  
  The most interesting result came while exploring the theme of violence. The industrial revolution caused a lot of class tensions which would often result in outbreaks of violence. When looking up the word "fight", corpus 1 returned the words "man" and "duel". This shows fighting to be an individual activity and not a group activity. When the same word was looked up in corpus 2, we found  that violence was associated with "King", "English" and "great". These words show a group mentality when it comes to violence, i.e., violence executed at scale by a formal power. Similar trends were seen with other words too. "Riot" was associated with "debauchery" and "dissipation" in corpus 1, but in corpus 2 we again see group dynamics come into play as we see it being associated with "arose", "altogether" and "assemblages". Here we see a certain unified-ness being attributed to the word riot. Even with the word "mob", while nothing of interest came up in corpus 1, in corpus 2, "mob" was associated with "bethinking" which gives mobs a thinking quality. Again for a mob to be thinking, the prerequisite is for it to be unified. 

  While these are interesting findings, it would be a longshot to say that they are significant. An uptick in violence or even a change in its nature does not signify that this had a lot to do with the industrial revolution. In the same time period, the UK experienced the potato famine, new taxation policies and also a general lack of faith in their declining colonial power. Any one of these incidents (or all of them together) could offer possible explanations as to why we see a change in the nature of violence.
  
*Corpus 1:* 

<iframe style='width: 509px; height: 358px;' src='https://voyant-tools.org/tool/CorpusTerms/?query=hunger*&query=hunger&query=hungry*&query=servant*&query=servant&query=poor*&query=poor&query=riot*&query=riot&query=crime*&query=violence*&query=mob*&query=fight*&query=sick*&query=violence&corpus=b3759ac665b9ae81bf04e31421f23781'data-external='1'></iframe> 

*Corpus 2:* 

<iframe style='width: 509px; height: 358px;' src='https://voyant-tools.org/tool/CorpusTerms/?query=hunger*&query=hunger&query=servant*&query=servant&query=poor*&query=poor&query=violence*&query=riot*&query=fight*&query=fight&query=mob*&query=crime&corpus=321ac1c06fcf8d0c249f71294d7f8f0a'data-external='1'></iframe> 

**Tool 3: DreamScape**
	In another attempt to find a trend before and after the Revolutions of 1848, we looked at the DreamScape option. This option allowed us to look at the trends in geographical references by adding two different filters with Corpus 1 & Corpus 2. Ideally, we would have benefited from visually representing the trends in connections to and from specific countries, coupled with their frequency, but this was the closest we could get. This is important to analyse due to the historical context of our research question itself. The Republican revolts leading to revolutions in the countries of France, Germany, Italy, and Austria were at the center of the conflict we are analysing the effect of, therefore it is safe to assume that references to these country names or citizens would increase after 1848. Hence, we made the DreamScape to represent the mapping, which we found to be more or less similar in both corpora. 

<iframe style='width: 477px; height: 348px;' src='https://voyant-tools.org/tool/DreamScape/?corpus=affb58168dd59d2a279b36e264b6829c'data-external='1'></iframe>

  We then used the earlier frequency tool for references to the 4 countries, where we saw a significant rise in the peaks in novels after 1848, using:

france|french|ital*|austria*|german*

<iframe style='width: 477px; height: 348px;' src='https://voyant-tools.org/tool/Trends/?query=france%7Cfrench%7Cital*%7Caustria*%7Cgerman&corpus=affb58168dd59d2a279b36e264b6829c'data-external='1'></iframe>

  The highest references were in A Child’s History of England, written in 1851, which makes sense due to the theme of the book. 

**Conclusion**
  The results of our analysis nullify our hypothesis, since we see very clearly the underwhelming impact of the Revolutions of 1848 on Dickens’ use of words, correlations, and geographical coverage. We do see an increase in references to the countries that were hit by conflict in 1848. In conclusion, it seems as though social upheavals impacted Dickens’ writing less than one might assume, or maybe there is an impact on a much deeper level that can be captured with more advanced tools.

**Reflection**
  This exercise offered us a unique opportunity of exploring the impact of a historical social event on the specifics of an author’s writing, something neither of us had thought was possible with historical, physical novels before this course due to the dense nature of books. Because of Dickens’ appeal to the ‘popular choices’ of the masses, it made intuitive sense that the content of his books would be moulded with what was most talked about. Several things happened during his lifetime that could count as important, historical events, but the Revolutions of 1848 happened to be in the middle so we can have enough books in each corpus. We also spent a lot of time trying to figure out the different themes to look at in order to see Dickens’ focus on different concepts, including class, labour, food, houses, staff, and emotions. Surely, it was disappointing to see our hypothesis nullified, but that makes it all the more interesting: How can a historical event so huge, that was increasingly flaming aggression in the middle class, not have been something Dickens took advantage of? Maybe appealing to the masses is not what he was focusing on. 
  
  Voyant as a tool is certainly important and helpful, but the process of not finding results we hypothesized makes us wonder: Is there an easier way? The user interface of Voyant itself is highly taxing, there is so much happening all in one screen, with a lot more hidden away. The weaknesses of Voyant as an analysis tool manifest in this incongruence, as changes in thematic elements of books cannot be captured simply by examining trends in word and word cluster frequency, there is more happening there. 
  
**Works Cited**
  Jann, Rosemary. “FACT, FICTION, AND INTERPRETATION IN ‘A CHILD’S HISTORY OF ENGLAND.’” Dickens Quarterly, vol. 4, no. 4, The Johns Hopkins University Press, 1987, pp. 199–205, http://www.jstor.org/stable/45291213.

  “Dickens: Law and Politics.” it.info. https://crossref-it.info/textguide/great-expectations/5/416. Accessed 16 Sept. 2021.

  Bowen, John. “Great Expectations and Class.” British Library, 15 May 2014, https://www.bl.uk/romantics-and-victorians/articles/great-expectations-and-class. Accessed 16 Sept. 2021.

  Griffin, Emma. “Child Labour.” The British Library, 15 May 2014, www.bl.uk/romantics-and-victorians/articles/child-labour. Accessed 16 Sept. 2021.

  The Editors of Encyclopaedia Britannica. “Revolutions of 1848.” Britannica, www.britannica.com/event/Revolutions-of-1848. Accessed 19 Sept. 2021.

  Shihada, Isam. “Capitalism in Charles Dickens’s Great Expectations: A Critique.” International Journal of English: Literature, Language & Skills, vol. 6, no. 1, Apr. 2017, pp. 42–52.